port: 8080
server: "sampleflut.de"
# The maximum length of a selected sample chunk in seconds (unlimited if ommited)
# If a long length is selected, the sample length will be limited by the server.
max_sample_length: 8
# The median delay in milliseconds per sample
sample_delay: 1000
files:
  - path: ./tracks/crazy.wav
    start_offset: 40
    volume_adjustment: 0.4
  - path: ./tracks/duck_song.wav
    start_offset: 20
  - path: ./tracks/heya.wav
    start_offset: 40
  - path: ./tracks/kacke.wav
    start_offset: 120
  - path: ./tracks/kohle.wav
    start_offset: 20
    end_offset: 10
  - path: ./tracks/never_gonna.wav
    start_offset: 60
    end_offset: 20
  - path: ./tracks/Tric_City.wav
    start_offset: 60
    end_offset: 20
    volume_adjustment: 0.8
  - path: ./tracks/yipee.wav
    start_offset: 5
    volume_adjustment: 0.8
